// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class AutocompleteHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject autocompleteHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.AutocompleteHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Input("Input"),
		SearchValue("SearchValue"),
		AutocompleteHelper_Collection("MyFirstModule.AutocompleteHelper_Collection");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AutocompleteHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.AutocompleteHelper"));
	}

	protected AutocompleteHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject autocompleteHelperMendixObject)
	{
		if (autocompleteHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.AutocompleteHelper", autocompleteHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.AutocompleteHelper");

		this.autocompleteHelperMendixObject = autocompleteHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AutocompleteHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.AutocompleteHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.AutocompleteHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.AutocompleteHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.AutocompleteHelper(context, mendixObject);
	}

	public static myfirstmodule.proxies.AutocompleteHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.AutocompleteHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Input
	 */
	public final java.lang.String getInput()
	{
		return getInput(getContext());
	}

	/**
	 * @param context
	 * @return value of Input
	 */
	public final java.lang.String getInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Input.toString());
	}

	/**
	 * Set value of Input
	 * @param input
	 */
	public final void setInput(java.lang.String input)
	{
		setInput(getContext(), input);
	}

	/**
	 * Set value of Input
	 * @param context
	 * @param input
	 */
	public final void setInput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String input)
	{
		getMendixObject().setValue(context, MemberNames.Input.toString(), input);
	}

	/**
	 * @return value of SearchValue
	 */
	public final java.lang.String getSearchValue()
	{
		return getSearchValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchValue
	 */
	public final java.lang.String getSearchValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchValue.toString());
	}

	/**
	 * Set value of SearchValue
	 * @param searchvalue
	 */
	public final void setSearchValue(java.lang.String searchvalue)
	{
		setSearchValue(getContext(), searchvalue);
	}

	/**
	 * Set value of SearchValue
	 * @param context
	 * @param searchvalue
	 */
	public final void setSearchValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchvalue)
	{
		getMendixObject().setValue(context, MemberNames.SearchValue.toString(), searchvalue);
	}

	/**
	 * @return value of AutocompleteHelper_Collection
	 */
	public final myfirstmodule.proxies.Collection getAutocompleteHelper_Collection() throws com.mendix.core.CoreException
	{
		return getAutocompleteHelper_Collection(getContext());
	}

	/**
	 * @param context
	 * @return value of AutocompleteHelper_Collection
	 */
	public final myfirstmodule.proxies.Collection getAutocompleteHelper_Collection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Collection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutocompleteHelper_Collection.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Collection.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutocompleteHelper_Collection
	 * @param autocompletehelper_collection
	 */
	public final void setAutocompleteHelper_Collection(myfirstmodule.proxies.Collection autocompletehelper_collection)
	{
		setAutocompleteHelper_Collection(getContext(), autocompletehelper_collection);
	}

	/**
	 * Set value of AutocompleteHelper_Collection
	 * @param context
	 * @param autocompletehelper_collection
	 */
	public final void setAutocompleteHelper_Collection(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Collection autocompletehelper_collection)
	{
		if (autocompletehelper_collection == null)
			getMendixObject().setValue(context, MemberNames.AutocompleteHelper_Collection.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutocompleteHelper_Collection.toString(), autocompletehelper_collection.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return autocompleteHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.AutocompleteHelper that = (myfirstmodule.proxies.AutocompleteHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.AutocompleteHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
